from vnpy_ctastrategy import (
    CtaTemplate,
    StopOrder,
    TickData,
    BarData,
    TradeData,
    OrderData,
    BarGenerator,
    ArrayManager,
)
from vnpy.trader.constant import Interval
from datetime import time


class StrategyTemplate(CtaTemplate):
    author = "AutoGenerated"

    sample_param = 10
    fixed_size = 1
    account_id = ""

    sample_value = 0.0
    entry_price = None

    parameters = ["sample_param", "fixed_size", "account_id"]
    variables = ["sample_value", "entry_price"]

    def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)
        self.bg = BarGenerator(self.on_bar)
        self.am = ArrayManager()

    def on_init(self) -> None:
        self.write_log("策略初始化")
        self.load_bar(10)

    def on_start(self) -> None:
        self.write_log("策略启动")
        self.put_event()

    def on_stop(self) -> None:
        self.write_log("策略停止")
        self.put_event()

    def on_tick(self, tick: TickData) -> None:
        self.bg.update_tick(tick)

    def on_bar(self, bar: BarData) -> None:
        self.cancel_all()
        self.am.update_bar(bar)
        if not self.am.inited:
            return
        self.put_event()

    def on_order(self, order: OrderData) -> None:
        pass

    def on_trade(self, trade: TradeData) -> None:
        if self.pos != 0:
            self.entry_price = trade.price
        else:
            self.entry_price = None
        self.put_event()

    def on_stop_order(self, stop_order: StopOrder) -> None:
        pass


class MultiTimeframeStrategyTemplate(CtaTemplate):
    author = "AutoGenerated"

    fast_window = 10
    slow_window = 20
    fixed_size = 1
    account_id = ""
    daily_end_hour = 14
    daily_end_minute = 59

    fast_ma = 0.0
    slow_ma = 0.0
    prev_fast_ma = None
    prev_slow_ma = None
    entry_price = None

    parameters = ["fast_window", "slow_window", "fixed_size", "account_id", "daily_end_hour", "daily_end_minute"]
    variables = ["fast_ma", "slow_ma", "prev_fast_ma", "prev_slow_ma", "entry_price"]

    def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)
        self.bg = BarGenerator(self.on_bar)
        self.am = ArrayManager()
        self.bg_daily = BarGenerator(
            self.on_bar,
            1,
            self.on_daily_bar,
            Interval.DAILY,
            daily_end=time(self.daily_end_hour, self.daily_end_minute)
        )
        self.am_daily = ArrayManager(max(self.slow_window + 10, 2))

    def on_init(self) -> None:
        self.write_log("策略初始化")
        self.load_bar(max(self.slow_window + 40, 90))

    def on_start(self) -> None:
        self.write_log("策略启动")
        self.put_event()

    def on_stop(self) -> None:
        self.write_log("策略停止")
        self.put_event()

    def on_tick(self, tick: TickData) -> None:
        self.bg.update_tick(tick)

    def on_bar(self, bar: BarData) -> None:
        self.cancel_all()
        self.am.update_bar(bar)
        if not self.am.inited:
            return
        self.bg_daily.update_bar(bar)
        if not self.am_daily.inited:
            self.put_event()
            return
        self.put_event()

    def on_daily_bar(self, bar: BarData) -> None:
        self.am_daily.update_bar(bar)
        if not self.am_daily.inited:
            return
        self.fast_ma = self.am_daily.ema(self.fast_window)
        self.slow_ma = self.am_daily.ema(self.slow_window)
        prev_fast = self.prev_fast_ma
        prev_slow = self.prev_slow_ma
        if prev_fast is not None and prev_slow is not None:
            if prev_fast <= prev_slow and self.fast_ma > self.slow_ma:
                if self.pos < 0:
                    self.cover(bar.close_price, abs(self.pos))
            elif prev_fast >= prev_slow and self.fast_ma < self.slow_ma:
                if self.pos > 0:
                    self.sell(bar.close_price, abs(self.pos))
        self.prev_fast_ma = self.fast_ma
        self.prev_slow_ma = self.slow_ma
        self.put_event()

    def on_order(self, order: OrderData) -> None:
        pass

    def on_trade(self, trade: TradeData) -> None:
        if self.pos != 0:
            self.entry_price = trade.price
        else:
            self.entry_price = None
        self.put_event()

    def on_stop_order(self, stop_order: StopOrder) -> None:
        pass
